### ISSUE TITLE
Issue to build llama.cpp with CMAKE

### ISSUE THREAD

**Issue by diegomontania** [abgulati/LARS#1]
Hi team, how you guys going?

First of all, thanks for this awesome tool, i am trying test in my current machine, with RTX 3060TI (Driver 555.85 - Cuda 12.2.2)

I am facing some issues to install.

I tried to add to a Path 'C:\Program Files\CMake\bin' and I got the same error.

First : 
![SystemVariables_Local](https://github.com/abgulati/LARS/assets/32251732/7db837a0-8cda-4677-a499-ce990683d743)

Second : 
![SystemVariables](https://github.com/abgulati/LARS/assets/32251732/b1cd9c3a-547e-4d28-9b2b-19458417b684)

Error :
![error](https://github.com/abgulati/LARS/assets/32251732/5dac3f3c-a3da-469b-b4a3-73ca24945603)

Drivers and cuda : 
[
![drivers and cuda](https://github.com/abgulati/LARS/assets/32251732/c911f1e3-d45b-4a23-a0e4-8e4264b7d09a)
](url)

After not working in the 'local user', I deleted it. And created in the second session 'system path'. But still not working. 
What am I doing wrong?

**Comment by abgulati** [comment]
Hi @diegomontania ,

On running 'cmake -B build -DLLAMA_CUDA=ON', the very first line you should see will be some variant of "-- Building for: Visual Studio 17 2022"

Make sure you have installed Build Tools, and when attempting to use Nvidia CUDA as you are, make sure you've implemented the CMAKE-CUDA fix, as specified in Steps 0 and 1 respectively in the [Dependencies](https://github.com/abgulati/LARS?tab=readme-ov-file#dependencies) section of the README.

Do confirm if you've carried out these steps. Once done, confirm the following:

1. That you've installed CMAKE correctly: type 'cmake' into a terminal window and ensure you don't get an "unrecognized command" output
2. That you've added CMAKE to the System Variable PATH, not the user variables PATH
3. Use the "Move Up" button on the right to move cmake to the top of the list of System PATH variables to ensure there isn't a conflict

Do carry out these steps and respond in detail if any issue still persists.

Cheers!

**Comment by diegomontania** [comment]
I dont have the path `C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\BuildCustomizations`

I have : `C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VisualStudio\v17.0\MSBuildExtensions`

This different path, maybe is the cause of the problem?

**Comment by abgulati** [comment]
Yes the path will be slightly different on your machine, the path in the readme is for reference purpose only. Glad it was resolved!

**Comment by abgulati** [comment]
Please try deleting the llama.cpp folder, clone it once again and try cmake again. This may resolve  the “no such directory” error. Try this and in the meantime I’ll try searching around for this error.

**Comment by diegomontania** [comment]
I deleted the llama.cpp folder, reinstaled the Cmake (cmake-3.30.0-rc1-windows-x86_64.msi) and tried this two solutions 👍 

https://stackoverflow.com/a/48400271 and https://stackoverflow.com/a/41369994.

Still not working :(

**Comment by abgulati** [comment]
Hi Diego, I've dug into this issue and added an extensive  [Troubleshooting](https://github.com/abgulati/LARS/tree/main?tab=readme-ov-file#troubleshooting-installation-issues) section for this CMake issue. Please check it and work through the steps.

It's most likely an issue with your Microsoft vs_buildTools installation, I have updated the Dependencies section with more details as well. Do check the [Troubleshooting](https://github.com/abgulati/LARS/tree/main?tab=readme-ov-file#troubleshooting-installation-issues) section and let me know.

**Comment by abgulati** [comment]
Simply run the vs_buildTools installer again, click "Modify" and ensure the "Desktop development with C++" workload and optionals as outlines in Step 0 of the [Dependencies](https://github.com/abgulati/LARS/tree/main?tab=readme-ov-file#dependencies) section are checked.

**Comment by diegomontania** [comment]
Hi! The error changed :

```-- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.22631.
-- OpenMP found
-- CUDA found
-- The CUDA compiler identification is NVIDIA 12.2.140
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - failed
-- Check for working CUDA compiler: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.2/bin/nvcc.exe
-- Check for working CUDA compiler: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.2/bin/nvcc.exe - broken
CMake Error at C:/Program Files/CMake/share/cmake-3.30/Modules/CMakeTestCUDACompiler.cmake:59 (message):
  The CUDA compiler

    "C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.2/bin/nvcc.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: 'C:/Users/Diego/llama.cpp/build/CMakeFiles/CMakeScratch/TryCompile-2bjzpk'

    Run Build Command(s): "C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_55339.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
    MSBuild version 17.10.4+10fbfbf2e for .NET Framework
    Build started 6/9/2024 8:31:39 PM.

    Project "C:\Users\Diego\llama.cpp\build\CMakeFiles\CMakeScratch\TryCompile-2bjzpk\cmTC_55339.vcxproj" on node 1 (default targets).
    PrepareForBuild:
      Creating directory "cmTC_55339.dir\Debug\".
      Structured output is enabled. The formatting of compiler diagnostics will reflect the error hierarchy. See https://aka.ms/cpp/structured-output for more details.
      Creating directory "C:\Users\Diego\llama.cpp\build\CMakeFiles\CMakeScratch\TryCompile-2bjzpk\Debug\".
      Creating directory "cmTC_55339.dir\Debug\cmTC_55339.tlog\".
    InitializeBuildStatus:
      Creating "cmTC_55339.dir\Debug\cmTC_55339.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
      Touching "cmTC_55339.dir\Debug\cmTC_55339.tlog\unsuccessfulbuild".
    AddCudaCompileDeps:
      C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.40.33807\bin\HostX64\x64\cl.exe /E /nologo /showIncludes /TP /D__CUDACC__ /D__CUDACC_VER_MAJOR__=12 /D__CUDACC_VER_MINOR__=2 /D_WINDOWS /DCMAKE_INTDIR="Debug" /D_MBCS /DCMAKE_INTDIR="Debug" /I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2\bin" /I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2\include" /I. /FIcuda_runtime.h /c C:\Users\Diego\llama.cpp\build\CMakeFiles\CMakeScratch\TryCompile-2bjzpk\main.cu
    Project "C:\Users\Diego\llama.cpp\build\CMakeFiles\CMakeScratch\TryCompile-2bjzpk\cmTC_55339.vcxproj" (1) is building "C:\Users\Diego\llama.cpp\build\CMakeFiles\CMakeScratch\TryCompile-2bjzpk\cmTC_55339.vcxproj" (1:2) on node 1 (CudaBuildCore target(s)).
    CudaBuildCore:
      Compiling CUDA source file main.cu...
      cmd.exe /C "C:\Users\Diego\AppData\Local\Temp\tmpa0b0e33d6a434a24b8b730e0a5d10ffd.cmd"
      "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2\bin\nvcc.exe"  --use-local-env -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.40.33807\bin\HostX64\x64" -x cu    -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2\include"     --keep-dir cmTC_55339\x64\Debug  -maxrregcount=0   --machine 64 --compile -cudart static -Xcompiler="/EHsc -Zi -Ob0" -g  -D_WINDOWS -D"CMAKE_INTDIR=\"Debug\"" -D_MBCS -D"CMAKE_INTDIR=\"Debug\"" -Xcompiler "/EHsc /W1 /nologo /Od /FS /Zi /RTC1 /MDd /GR" -Xcompiler "/FdcmTC_55339.dir\Debug\vc143.pdb" -o cmTC_55339.dir\Debug\main.obj "C:\Users\Diego\llama.cpp\build\CMakeFiles\CMakeScratch\TryCompile-2bjzpk\main.cu"

      C:\Users\Diego\llama.cpp\build\CMakeFiles\CMakeScratch\TryCompile-2bjzpk>"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2\bin\nvcc.exe"  --use-local-env -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.40.33807\bin\HostX64\x64" -x cu    -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2\include"     --keep-dir cmTC_55339\x64\Debug  -maxrregcount=0   --machine 64 --compile -cudart static -Xcompiler="/EHsc -Zi -Ob0" -g  -D_WINDOWS -D"CMAKE_INTDIR=\"Debug\"" -D_MBCS -D"CMAKE_INTDIR=\"Debug\"" -Xcompiler "/EHsc /W1 /nologo /Od /FS /Zi /RTC1 /MDd /GR" -Xcompiler "/FdcmTC_55339.dir\Debug\vc143.pdb" -o cmTC_55339.dir\Debug\main.obj "C:\Users\Diego\llama.cpp\build\CMakeFiles\CMakeScratch\TryCompile-2bjzpk\main.cu"
    C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2\include\crt/host_config.h(164): fatal error C1189: #error:  -- unsupported Microsoft Visual Studio version! Only the versions between 2017 and 2022 (inclusive) are supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk. [C:\Users\Diego\llama.cpp\build\CMakeFiles\CMakeScratch\TryCompile-2bjzpk\cmTC_55339.vcxproj]
      main.cu
    C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\BuildCustomizations\CUDA 12.2.targets(799,9): error MSB3721: The command ""C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2\bin\nvcc.exe"  --use-local-env -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.40.33807\bin\HostX64\x64" -x cu    -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2\include"     --keep-dir cmTC_55339\x64\Debug  -maxrregcount=0   --machine 64 --compile -cudart static -Xcompiler="/EHsc -Zi -Ob0" -g  -D_WINDOWS -D"CMAKE_INTDIR=\"Debug\"" -D_MBCS -D"CMAKE_INTDIR=\"Debug\"" -Xcompiler "/EHsc /W1 /nologo /Od /FS /Zi /RTC1 /MDd /GR" -Xcompiler "/FdcmTC_55339.dir\Debug\vc143.pdb" -o cmTC_55339.dir\Debug\main.obj "C:\Users\Diego\llama.cpp\build\CMakeFiles\CMakeScratch\TryCompile-2bjzpk\main.cu"" exited with code 2. [C:\Users\Diego\llama.cpp\build\CMakeFiles\CMakeScratch\TryCompile-2bjzpk\cmTC_55339.vcxproj]
    Done Building Project "C:\Users\Diego\llama.cpp\build\CMakeFiles\CMakeScratch\TryCompile-2bjzpk\cmTC_55339.vcxproj" (CudaBuildCore target(s)) -- FAILED.
    Done Building Project "C:\Users\Diego\llama.cpp\build\CMakeFiles\CMakeScratch\TryCompile-2bjzpk\cmTC_55339.vcxproj" (default targets) -- FAILED.

    Build FAILED.

    "C:\Users\Diego\llama.cpp\build\CMakeFiles\CMakeScratch\TryCompile-2bjzpk\cmTC_55339.vcxproj" (default target) (1) ->
    "C:\Users\Diego\llama.cpp\build\CMakeFiles\CMakeScratch\TryCompile-2bjzpk\cmTC_55339.vcxproj" (CudaBuildCore target) (1:2) ->
    (CudaBuildCore target) ->
      C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2\include\crt/host_config.h(164): fatal error C1189: #error:  -- unsupported Microsoft Visual Studio version! Only the versions between 2017 and 2022 (inclusive) are supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk. [C:\Users\Diego\llama.cpp\build\CMakeFiles\CMakeScratch\TryCompile-2bjzpk\cmTC_55339.vcxproj]
      C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\BuildCustomizations\CUDA 12.2.targets(799,9): error MSB3721: The command ""C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2\bin\nvcc.exe"  --use-local-env -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.40.33807\bin\HostX64\x64" -x cu    -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2\include"     --keep-dir cmTC_55339\x64\Debug  -maxrregcount=0   --machine 64 --compile -cudart static -Xcompiler="/EHsc -Zi -Ob0" -g  -D_WINDOWS -D"CMAKE_INTDIR=\"Debug\"" -D_MBCS -D"CMAKE_INTDIR=\"Debug\"" -Xcompiler "/EHsc /W1 /nologo /Od /FS /Zi /RTC1 /MDd /GR" -Xcompiler "/FdcmTC_55339.dir\Debug\vc143.pdb" -o cmTC_55339.dir\Debug\main.obj "C:\Users\Diego\llama.cpp\build\CMakeFiles\CMakeScratch\TryCompile-2bjzpk\main.cu"" exited with code 2. [C:\Users\Diego\llama.cpp\build\CMakeFiles\CMakeScratch\TryCompile-2bjzpk\cmTC_55339.vcxproj]

        0 Warning(s)
        2 Error(s)

    Time Elapsed 00:00:00.48





  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:411 (enable_language)


-- Configuring incomplete, errors occurred!```

**Comment by abgulati** [comment]
This indicates an issue with your CMAKE-CUDA fix. Make sure you've copied all the four files from the following directory:

```C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2\extras\visual_studio_integration\MSBuildExtensions```

and Pasted them to the following directory:

```C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\BuildCustomizations```
![CMAKE-CUDA-FIX-2-FOLDERS](https://github.com/abgulati/LARS/assets/20061663/0ae9db85-40c4-490a-8b2a-1308f95d2c2e)

**Comment by diegomontania** [comment]
I did the "CMAKE-CUDA fix" before run the command on cmake, but still facing the issue. Sorry :(

**Comment by abgulati** [comment]
Hi @diegomontania ,

Regret the delayed response, I got tied up elsewhere!

Please try the below troubleshooting steps and let me know if & what worked:

1.  CUDA Toolkit Installation:

Ensure that the CUDA Toolkit is properly installed. Check that the paths to the CUDA Toolkit binaries and libraries are correctly set.

2. Environment Variables:

Make sure the PATH, CUDA_HOME, and other relevant environment variables are set correctly. For example:

```
set PATH=%PATH%;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2\bin
set CUDA_HOME=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2
```

3. Visual Studio Integration:

Ensure that the CUDA Toolkit is correctly integrated with Visual Studio. This can be verified by checking if the CUDA Toolkit appears in the Visual Studio IDE under Tools > Options > CUDA.

4. Compiler Compatibility:

Check the compatibility between the CUDA version and the Visual Studio version you are using. Sometimes newer CUDA versions might not be fully compatible with older Visual Studio versions and vice versa.

5. Check Compiler Output:

Please share the output log from the attempt to compile the test program. It's usually located at the ```CMakeFiles/CMakeError.log``` file within the build directory.

6. Sample Program Test:

Try to compile a simple CUDA program manually using nvcc to see if the problem is specific to your environment or your CMake setup. For example, create a simple test.cu file:

```
#include <iostream>
__global__ void kernel() { }
int main() {
    kernel<<<1, 1>>>();
    std::cout << "CUDA test program\n";
    return 0;
}
```

Then compile it manually:
```
nvcc test.cu -o test
```

Please try these steps and share your findings., thanks!

**Comment by abgulati** [comment]
Further @diegomontania , I fed in your entire error message into GPT-4o and it's given me the following:

"
The error message indicates that the CUDA compiler (nvcc) is unable to compile a simple test program because of a compatibility issue with the Microsoft Visual Studio version being used. The key part of the error is:

```
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2\include\crt/host_config.h(164): fatal error C1189: #error:  -- unsupported Microsoft Visual Studio version! Only the versions between 2017 and 2022 (inclusive) are supported!
```

This indicates that the CUDA version you are using (CUDA 12.2) does not support the version of Microsoft Visual Studio you have installed.

Here are the steps you can take to resolve this issue:

1. Check Visual Studio Version:
Ensure you are using a supported version of Visual Studio (2017, 2019, or 2022). If you are using a newer version, you might need to downgrade to one of the supported versions.

2. Use the -allow-unsupported-compiler Flag:
As suggested in the error message, you can use the -allow-unsupported-compiler flag to override the version check. This can be done by modifying your CMake configuration to include this flag. However, be aware that this may cause compilation failures or incorrect runtime execution.

To add this flag, modify your CMakeLists.txt to include:

```
set(CMAKE_CUDA_FLAGS "${CMAKE_CUDA_FLAGS} -allow-unsupported-compiler")
```

3. Ensure Correct Compiler Configuration:
Ensure that your environment is correctly set up to use the right compiler version. You can verify and set the correct paths in your environment variables.

4. Update CUDA or Visual Studio:
If possible, consider updating your CUDA toolkit to the latest version that might support newer Visual Studio versions, or ensure that your Visual Studio installation is fully updated within the supported versions.

**If you prefer a quick solution, adding the -allow-unsupported-compiler flag might get you past the immediate error, but for a more stable and long-term fix, aligning your Visual Studio version with the supported versions of CUDA is recommended.**

"

Hope this helps a bunch.

**Comment by abgulati** [comment]
Hey any updates too this? Hoping to have a resolution to close out this Issue thread and update the README to guide others.

**Comment by abgulati** [comment]
Several resolution steps shared and issue closed since no update received.
