### ISSUE TITLE
Error with the latest build, " Server-side error, could not start local LLM server in method local_llm_server_starter, encountered error:  local variable 'use_flash_attention_2' referenced before assignment" 

### ISSUE THREAD

**Issue by Kareem21** [abgulati/LARS#29]
![image](https://github.com/user-attachments/assets/6552a7b9-cf89-45cf-be48-d3fbe80ebc8d)

**Comment by Kareem21** [comment]
![image](https://github.com/user-attachments/assets/95175b79-5980-4da4-b45a-aa70167dd309)

**Comment by Kareem21** [comment]
Im currently on windows using your latest build with the latest requirements.txt.

**Comment by Kareem21** [comment]
It seems that also HF isnt running which could be causing this error?

**Comment by Kareem21** [comment]
Console logs are useless 
![image](https://github.com/user-attachments/assets/da424b16-d3e7-4c2b-85ff-6413219c44f5)
it says the EXACT same thing that the browser popup error says

**Comment by abgulati** [comment]
A minor patch has gone out today to address this specific issue with the use_flash_attention_2 launch-arg.

Thanks for bringing this to my attention!
