### ISSUE TITLE
Fedora 39: requirements installation fails on pywin32

### ISSUE THREAD

**Issue by emulated24** [abgulati/LARS#5]
Installation on Fedora 39 fails with:

`ERROR: Ignored the following versions that require a different python version: 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11
ERROR: Could not find a version that satisfies the requirement pywin32==306 (from versions: none)
ERROR: No matching distribution found for pywin32==306`

My environment:
`uname -r`
`6.8.11-200.fc39.x86_64`

`nvcc --version`
`nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Wed_Apr_17_19:19:55_PDT_2024
Cuda compilation tools, release 12.5, V12.5.40
Build cuda_12.5.r12.5/compiler.34177558_0`

`python3 --version`
`Python 3.11.9`

**Comment by ShaswatPanda** [comment]
@emulated24 Pywin is a python library for Windows distributions...
You will not find pywin32 on pypi for Linux

Simply remove the pywin32 line from the `requirements.txt` file and install

**Comment by Hisma** [comment]
there needs to be a requirements.txt file thats specific to windows & specific to linux.  
Also when I try to edit the requirements.txt file, it's not formatted correctly for linux so it comes up with garbage.  
![image](https://github.com/abgulati/LARS/assets/13650167/575bba21-f109-4896-aab3-20a4cc218186)
So the requirements file needs to be fixed, and all the windows-specific requirements need to be removed.

**Comment by ShaswatPanda** [comment]
Yeah, nano isn't working. I opened it in VS Code, and it works fine. 
We should remember that only a single developer is working on this project atm. Changes will be slow, so you can add required changes and apply for a PR

**Comment by abgulati** [comment]
Thanks @ShaswatPanda , appreciate your understanding and support here!

@emulated24 @Hisma , as @ShaswatPanda pointed out, simply remove any platform-incompliant packages that error out your pip install.

I did dockerize this app a while back, a very old LangChain version of it and likely encountered this error and dealt with it in the above manner and simply forgot about it.

Nonetheless, I will add a requirements_linux.txt and close this issue in a near-future release.

**Comment by abgulati** [comment]
Added a requirements_linux.txt, and also containerized the app and tested the file as working as the docker build and run completed successfully. Have added the dockerfile too, will be updating the README and release shortly.

Docker containers, like Ubuntu, are Debian-based. Fedora is RPM-based so your experience may be slightly different, but most likely the requirements file will work the same.

Closing this issue for now.

**Comment by abgulati** [comment]
Issues with Nano should be resolved with the latest release: encoding for all requirements files have been changed to UTF-8.
