### ISSUE TITLE
Only Loading pdfs

### ISSUE THREAD

**Issue by Hisma** [abgulati/LARS#6]
According to your documentation, as long as I have libreoffice installed, I can load office files, ie docx, etc. 
However, when I try to load a docx file, I can see from the logfiles it's still trying to upload it as a pdf and read it. 
See output below from `server_log.log` -
```2024-06-11 19:22:16,155:ERROR:

Unexpected error when converting file to PDF, encountered error:  [Errno 2] No such file or directory: 'unoconv'


2024-06-11 19:22:16,156:ERROR:

Could not initialize PDF reader, encountered error:  EOF marker not found


2024-06-11 19:22:16,156:ERROR:

Failed to extract text from the PDF document, even via fallback PyPDF2, encountered error:  EOF marker not found


2024-06-11 19:22:16,157:ERROR:

Could not read PDF, encountered error:  EOF marker not found


2024-06-11 19:22:16,157:ERROR:

Failed to extract images from the PDF document, encountered error:  EOF marker not found


2024-06-11 19:22:16,157:ERROR:

Failed to save images to database, encountered error:  cannot access local variable 'images' where it is not associated with a value


2024-06-11 19:22:16,157:ERROR:

Failed to load document for storage to VectorDB, encountered error:  Error loading <FileStorage: 'Full control of envitec system.docx' ('application/vnd.openxmlformats-officedocument.wordprocessingml.document')>


2024-06-11 19:22:16,157:ERROR:

Failed to extract text from PDF:  Error loading <FileStorage: 'Full control of envitec system.docx' ('application/vnd.openxmlformats-officedocument.wordprocessingml.document')>


2024-06-11 19:22:16,160:ERROR:

Unable to record document loading to records DB, encountered error:  cannot access local variable 'chunk_size' where it is not associated with a value
```

libreoffice is confirmed to be installed.
![image](https://github.com/abgulati/LARS/assets/13650167/03d832c0-30a2-4463-9c71-075d3c36ce0d)

Not sure what else is missing.  What is the deal with the `no such file or directory 'unoconv'` error?  

Loading pdfs works just fine but as of now that's all that works.

**Comment by abgulati** [comment]
Ensure that the below file is in the web_app directory as it is in the repo:

https://github.com/abgulati/LARS/blob/main/web_app/unoconv.py

**Comment by abgulati** [comment]
README Documentation specifies to clone the entire repo! Do confirm if the above file is present.

**Comment by Hisma** [comment]
I have the file.  I actually tried to run the script and I found out it was missing some dependencies.  
I'm now stuck with this error and can't seem to get it to go away. 
![image](https://github.com/abgulati/LARS/assets/13650167/e51542ae-9382-4bf4-8646-95168c11f7f9)

So even though I can run libreoffice by itself (it even launches properly in xterm), there seems to be an issue with unoconv recognizing my installation.  I'm going to try to troubleshoot this unoconv issue as it seems to be a separate application that has its own github, and then come back and let you know if/how I got it working.  By that point it should hopefully work.

**Comment by Hisma** [comment]
Got it working.  I did so by installing the latest version of libreoffice (may not have been necessary) -
`sudo apt-add-repository ppa:libreoffice/ppa`
`sudo apt update`
`sudo apt install libreoffice`
This installed the latest version of libreoffice.  
Now you need to set the UNO_PATH environment variable to point to your libreoffice install path (this is probably the key part).  This is how I did it - 

`nano /etc/environment`

`UNO_PATH=/opt/libreoffice24.2`

`source ~/.bashrc`

Now it works.  
I would recommend adding "setting UNO_PATH" to the troubleshooting section if unoconv is not working.   The instructions I gave above should work for most cases for linux/wsl2 users.

**Comment by abgulati** [comment]
Thank you for sharing, I'll look into it and update the documentation as required. Glad it worked out for you!
