### ISSUE TITLE
requirements.txt is UTF-16LE encoding

### ISSUE THREAD

**Issue by jabberjabberjabber** [abgulati/LARS#8]
Please change encoding to UTF-8. As it is, without converting the encoding it cannot be edited using nano and using cat will output weird BOM at the beginning. If this is chosen for a particular reason and I am doing something wrong please let me know -- I am certainly not the expert on document encodings but this is a first seeing this for me. 

![Screenshot 2024-06-15 124556](https://github.com/abgulati/LARS/assets/75267439/688563d8-b64e-4a67-b84b-da0e467ba019)

**Comment by abgulati** [comment]
Hi, 

Thank you for bringing this to my attention! I have changed the encoding of all the requirements.txt files to UTF-8 and you should not have an issue with Nano anymore.

Closing this issue. Thanks again!
